Repository fishyboteso/fishyboteso, pull requests merged in 2021-04, with the labels that each got.

#61 remove label from fishingmode for logging
  fishy/engine/semifisher/engine.py
Labels: bug, next release

#63 Make call_in_thread fifo
  fishy/gui/gui.py
Labels: bug, next release

#62 Set auto_collect always enabled
  fishy/engine/semifisher/fishing_event.py
  fishy/gui/config_top.py
Labels: addon, next release

#60 remove uninstallation of old addons
  fishy/__main__.py
Labels: addon, next release

#59 remove sleep before fishing, with bugfix in chalutier 1.1.3
  fishy/engine/semifisher/fishing_mode.py
Labels: addon, next release

#66 Full auto engine
  fishy/constants.py
  fishy/engine/fullautofisher/calibrator.py
  fishy/engine/fullautofisher/controls.py
  fishy/engine/fullautofisher/engine.py
  fishy/engine/fullautofisher/player.py
  fishy/engine/fullautofisher/qr_detection.py
  fishy/engine/fullautofisher/recorder.py
  fishy/engine/fullautofisher/tesseract.py
  fishy/engine/semifisher/engine.py
  fishy/helper/downloader.py
  fishy/helper/hotkey_process.py
  requirements.txt
Labels: addon, feature, next release
