Repository fishyboteso/fishyboteso, pull requests merged in 2021-03, with the labels that each got.

#39 update uid on discord login, and fetch uid from config (never cache it) (0.4.4)
  fishy/engine/semifisher/fishing_event.py
  fishy/gui/config_top.py
  fishy/gui/discord_login.py
  fishy/gui/main_gui.py
  fishy/web/web.py
Labels: next release

#38 Remove fooaddon (0.4.4)
  MANIFEST.in
  fishy/FooAddon.zip
  fishy/__main__.py
Labels: next release

#37 Auto-Update: Add user interaction before updating (0.4.4)
  fishy/__main__.py
  fishy/engine/semifisher/fishing_event.py
  fishy/gui/main_gui.py
  fishy/gui/splash.py
  fishy/gui/update_dialog.py
  fishy/helper/__init__.py
  fishy/helper/auto_update.py
  fishy/helper/config.py
  fishy/helper/helper.py
Labels: next release

#24 Update fishy version to 0.4.4
  fishy/__init__.py
Labels: next release

#45 Substitute Provisions Chalutier Addon with Chalutier by Sem(0.4.5)
  MANIFEST.in
  fishy/ProvisionsChalutier.zip
  fishy/__main__.py
  fishy/constants.py
  fishy/engine/semifisher/pixel_loc.py
  fishy/gui/main_gui.py
  fishy/helper/__init__.py
  fishy/helper/helper.py
  fishy/web/constants.py
  fishy/web/web.py
Labels: enhancement

#43 map fishy tightly to chalutier states (0.4.5)
  fishy/engine/semifisher/engine.py
  fishy/engine/semifisher/fishing_event.py
  fishy/engine/semifisher/fishing_mode.py
Labels: enhancement, next release

#46 Remove didnt start popup (0.4.5)
  fishy/engine/semifisher/engine.py
Labels: next release

#47 Improve ask for update popup (0.4.5)
  fishy/gui/update_dialog.py
Labels: bug, next release

#40 Sort json config file (0.4.5)
  fishy/helper/config.py
Labels: bug, next release

#50 Fix bug calling is_subbed
  fishy/engine/common/window.py
  fishy/engine/semifisher/fishing_event.py
  fishy/gui/config_top.py
  fishy/web/web.py
Labels: bug, next release

#49 Improve Addon handling
  fishy/__main__.py
  fishy/constants.py
  fishy/gui/main_gui.py
  fishy/helper/__init__.py
  fishy/helper/helper.py
Labels: enhancement, next release

#52 Add detection of color for invfull and nobait state
  fishy/constants.py
  fishy/engine/semifisher/fishing_event.py
  fishy/engine/semifisher/fishing_mode.py
Labels: enhancement, next release

#53 remove brackets
  fishy/gui/main_gui.py
Labels: bug, next release

#54 Fixup notification checkbox
  fishy/web/web.py
Labels: bug, next release

#55 remove FooAddon from addon folder
  fishy/__main__.py
Labels: next release

#44 Version update to 0.4.5
  fishy/__init__.py
Labels: next release
