Repository fishyboteso/fishyboteso, pull requests merged in 2021-05, with the labels that each got.

#69 Add a 100ms sleep to semifisher loop
  fishy/engine/semifisher/engine.py
Labels: Robustness, Semifisher, feature

#57 Change colors to rgb and read saved-variables from Chalutier Addon for color detection (0.4.6)
  fishy/constants.py
  fishy/engine/common/window_server.py
  fishy/engine/semifisher/engine.py
  fishy/engine/semifisher/fishing_event.py
  fishy/engine/semifisher/fishing_mode.py
  fishy/helper/__init__.py
  fishy/helper/helper.py
  fishy/helper/luaparser.py
Labels: addon, feature, next release

#65 playsound whenever user interaction is required
  fishy/engine/semifisher/engine.py
  fishy/engine/semifisher/fishing_event.py
  fishy/helper/__init__.py
  fishy/helper/helper.py
  fishy/helper/hotkey.py
  fishy/web/__init__.py
  fishy/web/web.py
Labels: feature, next release
